/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/4jt1x9b9Bmd
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Tenor_Sans } from 'next/font/google'
import { Chivo } from 'next/font/google'

tenor_sans({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"

export function Activity() {
  return (
    <div className="w-full max-w-5xl mx-auto">
      <main className="grid gap-6 p-4">
        <section>
          <h2 className="text-xl font-semibold">Activity Overview</h2>
          <div className="grid gap-4 mt-4">
            <div className="relative pl-6 after:absolute after:inset-y-0 after:w-px after:bg-muted-foreground/20 after:left-0 grid gap-10">
              <div className="flex items-start gap-4 text-sm relative">
                  <Avatar className="w-10 h-10 border">
                    <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                    <AvatarFallback>CN</AvatarFallback>
                  </Avatar>
                <div className="grid gap-1">
                  <div className="font-medium">June 20, 2024 - Went for a 6.2 mile run</div>
                  <div className="text-muted-foreground">Completed a 48 minute and 22 second run.</div>
                </div>
              </div>
              <div className="flex items-start gap-4 text-sm relative">
                  <Avatar className="w-10 h-10 border">
                    <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                    <AvatarFallback>CN</AvatarFallback>
                  </Avatar>
                <div className="grid gap-1">
                  <div className="font-medium">June 15, 2024 - Went for a 24.3 mile bike ride</div>
                  <div className="text-muted-foreground">Completed a 1 hour and 12 minute bike ride.</div>
                </div>
              </div>
              <div className="flex items-start gap-4 text-sm relative">
                  <Avatar className="w-10 h-10 border">
                    <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                    <AvatarFallback>CN</AvatarFallback>
                  </Avatar>
                <div className="grid gap-1">
                  <div className="font-medium">June 10, 2024 - Went on an 8.1 mile hike</div>
                  <div className="text-muted-foreground">Completed a 2 hour and 45 minute hike.</div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
