/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MyCampaignsImport } from './routes/my-campaigns'
import { Route as AboutImport } from './routes/about'
import { Route as HomeImport } from './routes/Home'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const MyCampaignsRoute = MyCampaignsImport.update({
  path: '/my-campaigns',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const HomeRoute = HomeImport.update({
  path: '/Home',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/Home': {
      id: '/Home'
      path: '/Home'
      fullPath: '/Home'
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/my-campaigns': {
      id: '/my-campaigns'
      path: '/my-campaigns'
      fullPath: '/my-campaigns'
      preLoaderRoute: typeof MyCampaignsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  HomeRoute,
  AboutRoute,
  MyCampaignsRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/Home",
        "/about",
        "/my-campaigns"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/Home": {
      "filePath": "Home.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/my-campaigns": {
      "filePath": "my-campaigns.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
