/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProfileSettingsImport } from './routes/profile-settings'
import { Route as ProfileNotificationsImport } from './routes/profile-notifications'
import { Route as CampaingformtreestepImport } from './routes/campaingformtreestep'
import { Route as CampaingformsecondstepImport } from './routes/campaingformsecondstep'
import { Route as AboutImport } from './routes/about'
import { Route as CampaingCreateImport } from './routes/CampaingCreate'
import { Route as CampaignsImport } from './routes/Campaigns'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ProfileSettingsRoute = ProfileSettingsImport.update({
  path: '/profile-settings',
  getParentRoute: () => rootRoute,
} as any)

const ProfileNotificationsRoute = ProfileNotificationsImport.update({
  path: '/profile-notifications',
  getParentRoute: () => rootRoute,
} as any)

const CampaingformtreestepRoute = CampaingformtreestepImport.update({
  path: '/campaingformtreestep',
  getParentRoute: () => rootRoute,
} as any)

const CampaingformsecondstepRoute = CampaingformsecondstepImport.update({
  path: '/campaingformsecondstep',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const CampaingCreateRoute = CampaingCreateImport.update({
  path: '/CampaingCreate',
  getParentRoute: () => rootRoute,
} as any)

const CampaignsRoute = CampaignsImport.update({
  path: '/Campaigns',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/Campaigns': {
      id: '/Campaigns'
      path: '/Campaigns'
      fullPath: '/Campaigns'
      preLoaderRoute: typeof CampaignsImport
      parentRoute: typeof rootRoute
    }
    '/CampaingCreate': {
      id: '/CampaingCreate'
      path: '/CampaingCreate'
      fullPath: '/CampaingCreate'
      preLoaderRoute: typeof CampaingCreateImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/campaingformsecondstep': {
      id: '/campaingformsecondstep'
      path: '/campaingformsecondstep'
      fullPath: '/campaingformsecondstep'
      preLoaderRoute: typeof CampaingformsecondstepImport
      parentRoute: typeof rootRoute
    }
    '/campaingformtreestep': {
      id: '/campaingformtreestep'
      path: '/campaingformtreestep'
      fullPath: '/campaingformtreestep'
      preLoaderRoute: typeof CampaingformtreestepImport
      parentRoute: typeof rootRoute
    }
    '/profile-notifications': {
      id: '/profile-notifications'
      path: '/profile-notifications'
      fullPath: '/profile-notifications'
      preLoaderRoute: typeof ProfileNotificationsImport
      parentRoute: typeof rootRoute
    }
    '/profile-settings': {
      id: '/profile-settings'
      path: '/profile-settings'
      fullPath: '/profile-settings'
      preLoaderRoute: typeof ProfileSettingsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  CampaignsRoute,
  CampaingCreateRoute,
  AboutRoute,
  CampaingformsecondstepRoute,
  CampaingformtreestepRoute,
  ProfileNotificationsRoute,
  ProfileSettingsRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/Campaigns",
        "/CampaingCreate",
        "/about",
        "/campaingformsecondstep",
        "/campaingformtreestep",
        "/profile-notifications",
        "/profile-settings"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/Campaigns": {
      "filePath": "Campaigns.tsx"
    },
    "/CampaingCreate": {
      "filePath": "CampaingCreate.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/campaingformsecondstep": {
      "filePath": "campaingformsecondstep.tsx"
    },
    "/campaingformtreestep": {
      "filePath": "campaingformtreestep.tsx"
    },
    "/profile-notifications": {
      "filePath": "profile-notifications.tsx"
    },
    "/profile-settings": {
      "filePath": "profile-settings.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
